
from fpdf import FPDF
import datetime

class HealthReportPDF(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Anti-Gravity Health Monitoring Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(user_data, results, alerts, recs):
    """
    Generates a PDF report from health data.
    """
    pdf = HealthReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Date
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'R')
    pdf.ln(5)

    # 1. Patient Vitals
    pdf.set_font("Arial", 'B', 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "  Patient Vitals", 0, 1, 'L', fill=True)
    pdf.ln(2)
    
    pdf.set_font("Arial", size=11)
    vitals = [
        ("Age", f"{user_data['age']} years"),
        ("Gender", f"{user_data['gender']}"),
        ("Height", f"{user_data['height']} cm"),
        ("Weight", f"{user_data['weight']} kg"),
        ("BMI", f"{results['bmi']:.1f} ({results['bmi_cat']})"),
        ("Blood Pressure", f"{user_data['systolic']}/{user_data['diastolic']} mmHg"),
        ("Blood Sugar", f"{user_data['sugar']} mg/dL"),
        ("Heart Rate", f"{user_data['heart_rate']} bpm"),
    ]
    
    col_width = pdf.w / 2.5
    for label, value in vitals:
        pdf.cell(col_width, 8, f"{label}: {value}", 0, 1)

    pdf.ln(10)

    # 2. Risk Assessment
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "  Assessment Results", 0, 1, 'L', fill=True)
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 16)
    risk = results['risk_level']
    
    # Color logic
    if "High" in risk:
        pdf.set_text_color(220, 53, 69) # Red
    elif "Medium" in risk:
        pdf.set_text_color(255, 193, 7) # Orange/Yellow
    else:
        pdf.set_text_color(40, 167, 69) # Green
        
    pdf.cell(0, 10, f"Overall Risk Status: {risk}", 0, 1, 'C')
    
    pdf.set_text_color(0, 0, 0) # Reset color
    pdf.set_font("Arial", size=14)
    pdf.cell(0, 10, f"Health Score: {results['health_score']}/100", 0, 1, 'C')
    pdf.ln(5)

    # 3. Medical Alerts
    if alerts:
        pdf.set_font("Arial", 'B', 12)
        pdf.set_text_color(200, 0, 0)
        pdf.cell(0, 10, "Detected Medical Alerts:", 0, 1)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", size=11)
        
        for title, msg in alerts:
            pdf.cell(0, 7, f"- {title}: {msg}", 0, 1)
        pdf.ln(5)
            
    # 4. Recommendations
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Lifestyle Recommendations:", 0, 1)
    pdf.set_font("Arial", size=11)
    
    for rec in recs:
        pdf.multi_cell(0, 7, f"- {rec}")
        
    # Disclaimer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI system for educational purposes only. It does not constitute a medical diagnosis. Please consult a professional for medical advice.", 0, 'C')

    # Output to bytes
    return pdf.output(dest='S').encode('latin-1')
